Fixes #80
arkon/ng-inline-svg pull request #81
Opened 2018-06-07 11:07 UTC by AnimaMundi

Make all services singletons by providing them only through the forRoot method.

2018-06-07 11:25 UTC, dudyn5ky1 approved these changes

2018-06-07 11:25 UTC, dudyn5ky1 commented on demo/src/bootstrap.ts
> +class DemoAppModule { }
I think empty `{}` should be without space. This is not related to the change in this PR, but is good to consider and/or update `tslint` config with this

2018-06-07 11:34 UTC, JovicaConkic commented on demo/src/bootstrap.ts
> +class DemoAppModule { }
Don't worry. Microsoft allowed it.

2018-06-07 17:03 UTC, arkon commented on demo/src/bootstrap.ts
> +class DemoAppModule { }
Not sure what Microsoft has to do with it, but I'm fine with this.

2018-06-07 17:06 UTC, arkon requested changes

2018-06-07 17:06 UTC, arkon commented on src/svg-cache.service.ts
> +import { Injectable, Optional, Renderer2, RendererFactory2, Inject } from '@angular/core';
Minor nitpick: can you keep these sorted alphabetically?

2018-06-08 07:34 UTC, AnimaMundi commented on demo/src/bootstrap.ts
> +class DemoAppModule { }
He's making a reference to Microsoft's purchase of Github. Best to ignore this anyway 😄

2018-06-08 07:35 UTC, AnimaMundi commented on src/svg-cache.service.ts
> +import { Inject, Injectable, Optional, Renderer2, RendererFactory2 } from '@angular/core';
Sorted alphabetically now

2018-06-08 08:26 UTC, dudyn5ky1 commented on demo/src/bootstrap.ts
> +class DemoAppModule { }
@arkon in some parallel universe Github's acquisition is related to code style in `ng-*` directives, so that's fine.

2018-06-09 15:46 UTC, arkon approved these changes

2018-06-09 15:46 UTC, merged

2018-06-09 15:46 UTC, arkon commented
Thanks!

2018-06-09 16:03 UTC, arkon commented
Published as v8.0.0.

2018-06-09 21:29 UTC, AnimaMundi commented
Awesome, thanks for being so responsive!